// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://dkblvejwqbwhyjsryqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYmx2ZWp3cWJ3aHlqc3J5cXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjUzMjgsImV4cCI6MjA1NjQ0MTMyOH0.IcYCzA_yitfKsa6yVYmaAM5w_YFSC_Dhl9YqDnI-Fzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
